fail_fast: true
repos:

- repo: local
  hooks:
  - id: ruff
    name: ruff
    entry: ruff
    language: python
    types: [python]

  - id: pylint
    name: pylint
    entry: pylint
    language: python
    types: [python]

  - id: mypy
    name: mypy
    entry: mypy
    language: python
    types: [python]
    args: [--show-error-codes]

  - id: black
    name: black
    entry: black
    language: python
    types: [python]
    args: [--line-length=132]

  - id: pytest
    name: pytest
    entry: pytest
    language: python
    types: [python]
    pass_filenames: false
    always_run: true
