repos:

- repo: local
  hooks:
  - id: pylint
    name: pylint
    entry: pylint
    language: python
    types: [python]

- repo: local
  hooks:
  - id: mypy
    name: mypy
    entry: mypy
    language: python
    types: [python]
