repos:

- repo: local
  hooks:
  - id: pylint
    name: pylint
    entry: pylint
    args: ['--load-plugins', 'pylint_quotes']
    language: python
    types: [python]

  - id: mypy
    name: mypy
    entry: mypy
    language: python
    types: [python]
    args: [--show-error-codes]

  - id: isort
    name: isort
    entry: isort
    language: python
    types: [python]
    args: [-m, VERTICAL_HANGING_INDENT, --line-width=132, --fss, --ignore-whitespace, --trailing-comma, --check-only]

  - id: pytest
    name: pytest
    entry: pytest
    language: python
    types: [python]
    args: [test]
